ALTER TABLE products 
  ADD COLUMN IF NOT EXISTS allergens text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ingredients text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS calories integer DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS protein text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS carbs text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fat text DEFAULT NULL;